import Navbar from "@/components/Navbar";
import { FloatingChatbot } from "@/components/FloatingChatbot";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
} from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full`}
          suppressHydrationWarning
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* Layout wrapper */}
            <div className="flex min-h-screen w-full flex-col">
              <Navbar />

              {/* MAIN CONTENT AREA */}
              <main className="flex-1 w-full">
                {children}
              </main>
              <FloatingChatbot />
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
